In [1]:
import numpy as np

In [2]:
l = [234,456,567,-987,890]

In [3]:
np.array(l)

array([ 234,  456,  567, -987,  890])

In [5]:
np.array([12,3.4, True,"hello"])

array(['12', '3.4', 'True', 'hello'], dtype='<U32')

In [6]:
#arrays has homogenous data while lists can have heterogenous data

a = np.array([5,6,12,14])

In [7]:
a.mean()

9.25

In [8]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

---

All the following methods or functions are available for arrays

'all', 'any','argmax','argmin','argpartition','argsort','astype','base',
 'byteswap','choose','clip','compress','conj','conjugate','copy','ctypes',
 'cumprod','cumsum','data','diagonal','dot','dtype','dump','dumps','fill',
 'flags','flat','flatten','getfield','imag','item','itemset','itemsize',
 'max','mean','min','nbytes','ndim','newbyteorder','nonzero','partition',
 'prod','ptp','put','ravel','real','repeat','reshape','resize','round',
 'searchsorted','setfield','setflags','shape','size','sort','squeeze',
 'std','strides','sum','swapaxes','take','tobytes','tofile','tolist','tostring',
 'trace','transpose','var','view'

---

In [22]:
#Slicing Arrays
x = np.array([234,456,567,678,789])

In [23]:
x[::2]

array([234, 567, 789])

In [24]:
x[:]

array([234, 456, 567, 678, 789])

In [26]:
y = x[1:4]

In [27]:
y[:] = 22 

In [28]:
x

array([234,  22,  22,  22, 789])

If a change is made in slices, it is applied to original array